version: '3.8'

services:
  postgres:
    image: postgres:13
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"  # Убедитесь, что порт прокинут
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user_service
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DOCKER_ENV=true  # Добавлено для определения, что сервис запущен в Docker
    ports:
      - "8000:8000"
    networks:
      - app-network

  api-gateway:
    build: ./api_gateway
    depends_on:
      - user-service
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
